[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olaverse"
version = "0.1.5"
description = "Advanced ML infrastructure and interface to load and run all Olaverse models"
readme = "README.md"
authors = [
    { name = "Olaverse", email = "support@olaverse.co.uk" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.20.0",
    "requests>=2.25.0",
    "tqdm>=4.50.0",
    "tokenizers>=0.13.0",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "jupyter>=1.0.0",
    "scikit-learn>=1.0.0",
]
docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
]
legal = [
    "unsloth",
]
deeplearning = [
    "torch",
    "transformers",
]
hosted = [
    "openai>=1.0.0",
]
lid = [
    "fasttext-wheel",
]
retrieval = [
    "sentence-transformers",
]
data = [
    "datasets",
]
vision = [
    "torch",
    "torchvision",
    "Pillow",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["olaverse*"]

[tool.setuptools.exclude-package-data]
olaverse = ["models/*"]
